-- CreateEnum
CREATE TYPE "ReplyIntent" AS ENUM ('INTERESTED', 'NOT_INTERESTED', 'NEEDS_INFORMATION', 'REQUEST_CALL', 'REQUEST_PROPOSAL', 'FOLLOW_UP_LATER', 'PRICE_QUESTION', 'WRONG_CONTACT', 'OUT_OF_OFFICE', 'UNSUBSCRIBE', 'UNKNOWN');

-- AlterTable
ALTER TABLE "Reply" ADD COLUMN     "intent" "ReplyIntent",
ADD COLUMN     "intentConfidence" DOUBLE PRECISION,
ADD COLUMN     "suggestedResponse" TEXT;
